### ISSUE TITLE
UnboundLocalError: local variable 'help_text' referenced before assignment

### ISSUE THREAD

**Issue by RBSystems** [StephenGenusa/Crestron-Device-Documenter#1]
>Firmware version  DMPS3-4K-150-C Cntrl Eng [v1.502.3088.20962 (Jun 16 2017),x] x

Traceback (most recent call last):
  File "./BuildCrestronCommandReference.py", line 701, in <module>
    documenter.generate_documentation()
  File "./BuildCrestronCommandReference.py", line 667, in generate_documentation
    self.write_html_documentation()
  File "./BuildCrestronCommandReference.py", line 633, in write_html_documentation
    long_help = self.get_command_help(command)
  File "./BuildCrestronCommandReference.py", line 325, in get_command_help
    for line in help_text.split("\n"):
UnboundLocalError: local variable 'help_text' referenced before assignment

**Comment by RBSystems** [comment]
command is RCONPING

![screenshot](https://user-images.githubusercontent.com/17103021/30208424-0acf8a40-949c-11e7-97f7-579a17b5fd57.png)

**Comment by StephenGenusa** [comment]
Thank you for reporting this.

That command ignores the ? so I'd add an entry for it to your donotexec.upc file. I've modified the program and will be adding an updated EXE shortly.

Thank you again!
